### ISSUE TITLE
tsc as a Dev Dependency? & rimraf needs Global Install

### ISSUE THREAD

**Issue by devivekw** [sahilshaheen/ts-node-starter#1]
https://github.com/sahilshaheen/ts-node-starter/blob/a944e67014b44eaa717b548536ff3536cd48b007/package.json#L9

@sahilshaheen I see that you haven't installed `tsc` as a dependency in [package.json](https://github.com/sahilshaheen/ts-node-starter/blob/a944e67014b44eaa717b548536ff3536cd48b007/package.json#L16-L27) I am assuming this mean it comes prebuilt with `typescript` ?

And you forgot to mention user's on windows platform that `rimraf` needs to be installed as a global dependency.

**Comment by sahilshaheen** [comment]
Yeah, the compiler's included with TypeScript only. And I think it's enough to install rimraf as a dev dependency. Didn't find anything in their docs relating to a global install.

**Comment by devivekw** [comment]
> Yeah, the compiler's included with TypeScript only. And I think it's enough to install rimraf as a dev dependency. Didn't find anything in their docs relating to a global install.

Yeah I thought so too, but Widows has a similar issue with `nodemon` as well. It might just be a powershell thing.
